
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Cat = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Typing_TailWag.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="_EyeR"
          castShadow
          receiveShadow
          geometry={nodes._EyeR.geometry}
          material={materials['Material.002']}
          position={[-0.359, 2.362, 0.666]}
          scale={0.087}
        />
        <mesh
          name="_BrowR"
          castShadow
          receiveShadow
          geometry={nodes._BrowR.geometry}
          material={nodes._BrowR.material}
          position={[-0.442, 2.561, 0.604]}
          scale={[0.114, 0.014, 0.014]}
        />
        <mesh
          name="Collar"
          castShadow
          receiveShadow
          geometry={nodes.Collar.geometry}
          material={nodes.Collar.material}
          position={[0, 2.064, -0.41]}
          rotation={[-2.045, 0, -Math.PI]}
          scale={[-0.526, -0.056, -0.475]}
        />
        <mesh
          name="_EyeL"
          castShadow
          receiveShadow
          geometry={nodes._EyeL.geometry}
          material={materials['Material.002']}
          position={[0.359, 2.362, 0.666]}
          scale={0.087}
        />
        <mesh
          name="_BrowL"
          castShadow
          receiveShadow
          geometry={nodes._BrowL.geometry}
          material={nodes._BrowL.material}
          position={[0.442, 2.561, 0.604]}
          scale={[0.114, 0.014, 0.014]}
        />
        <group name="Armature">
          <skinnedMesh
            name="_Body"
            geometry={nodes._Body.geometry}
            material={materials['Material.001']}
            skeleton={nodes._Body.skeleton}
          />
          <primitive object={nodes.Root} />
          <primitive object={nodes.Tail} />
          <primitive object={nodes.Tail_IK} />
          <primitive object={nodes.PawR} />
          <primitive object={nodes.Paw_IKR} />
          <primitive object={nodes.PawL} />
          <primitive object={nodes.Paw_IKL} />
          <primitive object={nodes.neutral_bone} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Typing_TailWag.glb')

export default Cat;

