/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: totomori (https://sketchfab.com/totomori)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-little-star-1fc3bdccaad9455db5a9ed80f5a61cb9
Title: Cute little Star
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshToonMaterial, TextureLoader } from 'three'

const Star = (props) => {
  const { nodes } = useGLTF('/models/star.glb');

  // load the gradient map texture
  const textureLoader = new TextureLoader();
  const gradientMap = textureLoader.load('/images/textures/threeTone.jpg'); // gradient map 

  // MeshToonMaterial with the gradient map
  const toonMaterial = new MeshToonMaterial({
    color: '#69140E',  // color of the star
    gradientMap: gradientMap,  // apply the loaded gradient map texture
  });



  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={toonMaterial} 
            // material={materials['Material.008']}
            position={[0, 1.685, 0.454]}
            rotation={[1.716, 0.281, -0.174]}
            scale={[0.032, 0.066, 0.035]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={toonMaterial} 
            // material={materials['Material.007']}
            position={[0, 1.699, 0.484]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.031, 0.033, 0.033]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={toonMaterial} 
            // material={materials['Material.001']}
            position={[0, 1.67, 0.252]}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={toonMaterial} 
            // material={materials['Material.002']}
            position={[0, 1.758, 0.461]}
          />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/star.glb')
export default Star;

